# 绘制图结构
print("图结构分析:")
print("     3")
print("     |5")
print("1----2----?")
print("|4   |3")
print("4----6----7")
print("|7   |9   |6")
print("     5")
print()
print("等等，让我重新分析边的连接...")
print()
print("边列表:")
print("1-2 (4)")
print("1-4 (7)")
print("3-2 (5)")
print("7-6 (6)")
print("6-4 (9)")
print("4-5 (1)")
print()
print("所以图结构应该是:")
print("     3")
print("     |5")
print("1----2")
print("|4")
print("4----5")
print("|7   |1")
print("     6----7")
print("     |9   |6")
print()
print("从1到6的路径:")
print("1 -> 4 -> 6: 需要7体力到4，获得6体力变成6，需要9体力到6，不够，需要额外3体力，总计10")
print("1 -> 2 -> 3 -> ? (3不直接连到6)")
print()
print("等等，让我检查边的连接...")
